change options type to interface
alibaba-go/bluto pull request #11
Opened 2020-09-09 10:19 UTC by cep-ter

2020-09-12 10:04 UTC, bbmokhtari approved these changes

2020-09-12 10:04 UTC, bbmokhtari commented on commander/commander.go
> +type XPendingOptionStartEndCount struct {
Aren't these separate?

2020-09-13 11:00 UTC, rezakamalifard requested changes
- update current docs
- add an example for its usage and multiple usages to the readme doc 
- add tests for multiple option usages

2020-09-14 12:15 UTC, rezakamalifard approved these changes

2020-09-14 12:15 UTC, merged