change redis commands option type to pointer
alibaba-go/bluto pull request #3
Opened 2020-09-01 11:49 UTC by cep-ter

2020-09-07 09:43 UTC, bbmokhtari requested changes
Please check the comment and elaborate.

2020-09-07 09:43 UTC, bbmokhtari commented on commander/commander.go
> +		if options.Time.Unix() > 0 {
Please use the standard Redis interface integer instead of time types.

2020-09-07 09:43 UTC, bbmokhtari commented on commander/commander.go
> +		if options.RetryCount != 0 {
Please check the inconsistencies for types, specifically `int`. and also check the inconsistencies for operators, specially `>` and `!=`.

2020-09-08 05:55 UTC, bbmokhtari approved these changes

2020-09-08 14:04 UTC, rezakamalifard requested changes

2020-09-08 14:40 UTC, cep-ter commented on commander/commander_test.go
> +		XAdd(&xaddResult, streamNmae, "*", map[string]string{key: value}, nil).
The main purpose of this pr is to replace empty options with nil.
If you think this is not clear maybe we shouldn't change option type to pointer.

2020-09-08 14:53 UTC, cep-ter commented on commander/commander_bdd_test.go
> -				Set(&setResult, key, 9, SetOption{}).
I try to make it safer in run-time by restrict user to predefined option structs rather than variadic args

2020-09-12 11:07 UTC, closed without merging