feat add exists
alibaba-go/bluto pull request #6
Opened 2020-09-02 10:18 UTC by cep-ter

2020-09-07 09:48 UTC, bbmokhtari approved these changes

2020-09-08 10:57 UTC, rezakamalifard requested changes

2020-09-08 10:57 UTC, rezakamalifard commented on commander/commander_bdd_test.go
> +			errCmd := commander.Exists(&existsResult, "SomeKey1", "SomeKey2").Commit()
add a case for not exists key @cep-ter

2020-09-08 14:02 UTC, rezakamalifard approved these changes

2020-09-08 14:02 UTC, merged